//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> InsurerID { get; set; }
        public string Status { get; set; }
        public decimal MinimumCoverage { get; set; }
        public decimal MaximumCoverage { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
